-- Drop existing tables in correct dependency order
DROP TABLE IF EXISTS transactions;
DROP TABLE IF EXISTS blocks;
DROP TABLE IF EXISTS accounts;

-- Create accounts table
CREATE TABLE accounts (
    address         CHAR(42) PRIMARY KEY,
    name            VARCHAR(32) NOT NULL,
    password_hash   TEXT NOT NULL,
    sb_balance      NUMERIC(20,8) DEFAULT 0,
    tx_sent_count   INTEGER DEFAULT 0,
    refresh_token   TEXT
);

-- Create blocks table
CREATE TABLE blocks (
    height              INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 0 MINVALUE 0) PRIMARY KEY,
    timestamp           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    max_transactions    INTEGER NOT NULL,
    parent_hash         TEXT,
    hash                TEXT NOT NULL
);

-- Create transactions table
CREATE TABLE transactions (
    transaction_hash CHAR(66) PRIMARY KEY,
    block_height     INTEGER REFERENCES blocks(height),
    timestamp        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    from_address     CHAR(42) REFERENCES accounts(address),
    to_address       CHAR(42) REFERENCES accounts(address),
    value            NUMERIC(20,8) NOT NULL CHECK (value > 0)
);


INSERT INTO blocks (height, timestamp, max_transactions, parent_hash, hash)
VALUES 
(0, CURRENT_TIMESTAMP, 3,
 '0x0000000000000000000000000000000000000000000000000000000000000000',
 '0xd4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3')
ON CONFLICT (height) DO NOTHING;