apiVersion: apps/v1
kind: Deployment
metadata:
  name: stableblock-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stableblock-api
  template:
    metadata:
      labels:
        app: stableblock-api
    spec:
      containers:
      - name: stableblock-api
        image: stableblock-api:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: stableblock-config
        - secretRef:
            name: stableblock-secrets
